# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('cliente', 'cliente'), ('asesor', 'asesor'), ('reclutador', 'reclutador')], max_length=100, null=True),
        ),
    ]
