# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asesorId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
