# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_asesorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'cliente'), ('asesor', 'asesor'), ('reclutador', 'reclutador'), ('general', 'general')], default='general', max_length=100),
        ),
    ]
