# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170809_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clienteId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
