# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_clienteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('general', 'general'), ('cliente', 'cliente'), ('asesor', 'asesor'), ('reclutador', 'reclutador'), ('both', 'both')], default='cliente', max_length=100),
        ),
    ]
