# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170811_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(choices=[('general', 'general'), ('cliente', 'cliente'), ('asesor', 'asesor'), ('reclutador', 'reclutador'), ('both', 'both')], default='general', max_length=100),
        ),
    ]
