# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170901_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='analista',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jefe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reclutador',
            field=models.BooleanField(default=True),
        ),
    ]
