# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170913_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='analista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reclutador',
            field=models.BooleanField(default=False),
        ),
    ]
