# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_auto_20170830_1443'),
        ('asesores', '0002_auto_20170830_1336'),
    ]

    operations = [
    ]
