# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0003_merge_20170831_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos'),
        ),
    ]
