# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0004_auto_20170907_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='clave',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
