# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_remove_poliza_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='nombre',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
