# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_poliza_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='nombre',
        ),
    ]
