# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0005_remove_poliza_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_poliza',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
