# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0006_auto_20170716_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor_poliza', to=settings.AUTH_USER_MODEL),
        ),
    ]
