# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0009_auto_20170726_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='addaddress',
            field=models.BooleanField(default=False),
        ),
    ]
