# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0010_auto_20170726_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clavet', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo', models.CharField(blank=True, max_length=150, null=True)),
                ('puertas', models.CharField(blank=True, max_length=150, null=True)),
                ('ocupantes', models.CharField(blank=True, max_length=150, null=True)),
                ('placa', models.CharField(blank=True, max_length=150, null=True)),
                ('serie', models.CharField(blank=True, max_length=150, null=True)),
                ('motor', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('repuve', models.CharField(blank=True, max_length=150, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('uso', models.CharField(blank=True, max_length=150, null=True)),
                ('origen', models.CharField(blank=True, max_length=150, null=True)),
                ('conductor', models.CharField(blank=True, max_length=150, null=True)),
                ('prima_neta', models.CharField(blank=True, max_length=150, null=True)),
                ('prima_total', models.CharField(blank=True, max_length=150, null=True)),
                ('adaptaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('alta', models.CharField(blank=True, max_length=150, null=True)),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='polizas.Poliza')),
            ],
        ),
    ]
