# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0013_auto_20170814_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='last',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
