# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0014_poliza_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('poliza', models.ManyToManyField(blank=True, related_name='recibo_poliza', to='polizas.Poliza')),
            ],
        ),
    ]
