# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0015_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='poliza',
        ),
        migrations.AddField(
            model_name='recibo',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_poliza', to='polizas.Poliza'),
        ),
    ]
