# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0017_auto_20170816_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='derechos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='iva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='pago_frac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='prima_neta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='prima_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
