# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0018_auto_20170816_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('prod1', models.CharField(max_length=100)),
                ('prod2', models.CharField(max_length=100)),
                ('comentarios', models.TextField()),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospecto_asesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
