# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0021_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='asesor',
            name='reclutador',
        ),
        migrations.RemoveField(
            model_name='asesor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.RemoveField(
            model_name='clave',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='asesor',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Asesor',
        ),
        migrations.DeleteModel(
            name='Clave',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
