# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0022_auto_20170828_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poliza',
            old_name='daños',
            new_name='danhos',
        ),
        migrations.AddField(
            model_name='poliza',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idcliente',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='idpoliza',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
