# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0023_auto_20170905_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='carpeta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='emisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
